
30-11-2022 17:51:41
Traceback (most recent call last):
  File "C:\Users\lteru\Desktop\PhD\Green\eurocold\scripts\Abakus\main\abakus.pyw", line 276, in connect_widgets
    self.third_panel.btn_voltage_noise.clicked.connect(self.on_voltage_noise_plot_cicked)
AttributeError: 'Ui' object has no attribute 'on_voltage_noise_plot_cicked'

30-11-2022 17:51:50
Traceback (most recent call last):
  File "C:\Users\lteru\Desktop\PhD\Green\eurocold\scripts\Abakus\main\abakus.pyw", line 276, in connect_widgets
    self.third_panel.btn_voltage_noise.clicked.connect(self.on_voltage_noise_plot_cicked)
AttributeError: 'Ui' object has no attribute 'on_voltage_noise_plot_cicked'

30-11-2022 17:52:04
Traceback (most recent call last):
  File "C:\Users\lteru\Desktop\PhD\Green\eurocold\scripts\Abakus\main\abakus.pyw", line 274, in connect_widgets
    self.third_panel.btn_help.clicked.connect(self.on_help_clcked)
AttributeError: 'Ui' object has no attribute 'on_help_clcked'

06-12-2022 13:49:55
Traceback (most recent call last):
  File "C:\Users\lteru\Desktop\PhD\Green\eurocold\scripts\Abakus\main\abakus.pyw", line 403, in on_serial_clicked
    self.abakus = Abakus(self.first_panel.combobox_port.currentText())
  File "C:\Users/lteru/Desktop/PhD/Green/eurocold/scripts/Abakus/methods\abakus_class.py", line 45, in __init__
    self._dev = serial.Serial(port, baudrate, bytesize, parity, stopbits, timeout)              # Creation of a Abakus object with the specificed serial
  File "C:\Users\lteru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\lteru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Users\lteru\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port '': FileNotFoundError(2, 'Impossibile trovare il percorso specificato.', None, 3)
